/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Product product = new Product("product1", "product1 description", 25.50f);
        System.out.printf("Product name = %s, product description = %s, price = %2.2f", product.getName(), product.getDescription(), product.getPrice());
    }
}
